export const test_data = [
    {
        id: 1,
        test_id: "TST-8F2K91",
        key: "key1",
        hash_url: "hash1",
        ispublic: true,
        nom: "JavaScript Asoslari",
        tavsif: "JavaScript bo'yicha boshlang'ich darajadagi 20 ta test savoli.",
        fan: "Dasturlash",
        istime: true,
        time: "20 daqiqa",
        savollar_soni: 20,
        created: "09.07.2026",
        hashtag_names: ["javascript", "frontend", "beginner"]
    },
    {
        id: 2,
        test_id: "TST-A9P4X2",
        key: "key2",
        hash_url: "hash2",
        ispublic: true,
        nom: "React Hooks",
        tavsif: "useState, useEffect va boshqa hooklar bo'yicha test.",
        fan: "React",
        istime: false,
        time: "",
        savollar_soni: 15,
        created: "08.07.2026",
        hashtag_names: ["react", "hooks"]
    },
    {
        id: 3,
        test_id: "TST-QW98L2",
        key: "key3",
        hash_url: "hash3",
        ispublic: false,
        nom: "DTM Matematika 2026",
        tavsif: "Abituriyentlar uchun matematikadan namunaviy test.",
        fan: "Matematika",
        istime: true,
        time: "90 daqiqa",
        savollar_soni: 30,
        created: "05.07.2026",
        hashtag_names: ["dtm", "matematika", "abituriyent"]
    },
    {
        id: 4,
        test_id: "TST-HG5N3M",
        key: "key4",
        hash_url: "hash4",
        ispublic: true,
        nom: "Ingliz tili Grammar",
        tavsif: "English grammar bo'yicha Intermediate darajadagi test.",
        fan: "Ingliz tili",
        istime: true,
        time: "25 daqiqa",
        savollar_soni: 25,
        created: "01.07.2026",
        hashtag_names: ["english", "grammar", "intermediate"]
    },
    {
        id: 5,
        test_id: "TST-ZX73TR",
        key: "key5",
        hash_url: "hash5",
        ispublic: true,
        nom: "Python OOP",
        tavsif: "Object Oriented Programming mavzusiga oid savollar.",
        fan: "Python",
        istime: false,
        time: "",
        savollar_soni: 18,
        created: "30.06.2026",
        hashtag_names: ["python", "oop"]
    },
    {
        id: 6,
        test_id: "TST-KL12MN",
        key: "key6",
        hash_url: "hash6",
        ispublic: false,
        nom: "SQL SELECT va JOIN",
        tavsif: "SQL SELECT, WHERE, GROUP BY va JOIN operatorlari.",
        fan: "SQL",
        istime: true,
        time: "30 daqiqa",
        savollar_soni: 22,
        created: "28.06.2026",
        hashtag_names: ["sql", "database", "join"]
    },
    {
        id: 7,
        test_id: "TST-PL93YU",
        key: "key7",
        hash_url: "hash7",
        ispublic: true,
        nom: "Tarix - O'zbekiston",
        tavsif: "O'zbekiston tarixi bo'yicha umumiy bilim testi.",
        fan: "Tarix",
        istime: true,
        time: "40 daqiqa",
        savollar_soni: 35,
        created: "25.06.2026",
        hashtag_names: ["tarix", "uzbekiston"]
    },
    {
        id: 8,
        test_id: "TST-MN45QR",
        key: "key8",
        hash_url: "hash8",
        ispublic: true,
        nom: "CSS Flexbox va Grid",
        tavsif: "Flexbox va CSS Grid bo'yicha amaliy test.",
        fan: "CSS",
        istime: false,
        time: "",
        savollar_soni: 16,
        created: "20.06.2026",
        hashtag_names: ["css", "flexbox", "grid"]
    }
];

export const categor = [
    // "Matematika", 'DTM', 'Tarix', 'Fizika', 'Python', 'AI'
]